### ISSUE TITLE
Add a license

### ISSUE THREAD

**Issue by Calinou** [koczkatamas/onelang#24]
The [package.json](https://github.com/koczkatamas/onelang/blob/aefe3fac651fdfade714169f11bbbd1bfca1d06e/package.json#L26) hints at this project being licensed under the ISC license, but since it is the default choice set by `npm init`, it may have limited legal value.

Please consider adding an open source license; see [Choose a License](https://choosealicense.com/) for more informtaion. Thanks in advance :smiley:

**Comment by koczkatamas** [comment]
Yeah, sorry, I forgot to add one, I will add MIT license in an hour.

**Comment by Calinou** [comment]
Thanks! Can you also change the license field in `package.json`, please?

**Comment by koczkatamas** [comment]
Done. (note: changed other fields too)
