### ISSUE TITLE
https://ide.onelang.io/ is down

### ISSUE THREAD

**Issue by abitrolly** [koczkatamas/onelang#36]
https://ide.onelang.io/ is absent from the web,

**Comment by tst2005** [comment]
whois onelang.io
```
Creation Date: 2017-10-10T18:18:01Z
Updated Date: 2019-10-10T22:30:50Z
Registry Expiry Date: 2020-10-10T18:18:01Z
```

The date is close to yesterday. It could be a domain renew issue.

**Comment by koczkatamas** [comment]
Fixed, sorry for the inconvenience!
